name: Run tests

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      REGISTRY_AUTH_FILE: ${{ github.workspace }}/auth.json
    steps:
      - name: Create dummy auth file
        # this may be empty as we are fetching from public docker registry.
        run: echo '{}' > auth.json
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: direnv-nix
        uses: JRMurr/direnv-nix-action@v4.2.0
      - name: run tests
        run: just test
        shell: bash
